# ------------------------------------------------------------ #
# File: config.py
# Date: 2026-04-11
# Author: Florentino
# Description: Centralized path helpers for ITSE-1003 scripts.
# Explanation: It explains how to build stable course-local paths for data and generated files, independent of the current working directory.
# ------------------------------------------------------------ #

from pathlib import Path

# Absolute path to the course root folder: `labs/ITSE-1003`.
# We anchor paths to this file location to avoid issues when scripts are run
# from different working directories (repo root, IDE terminal, etc.).
ITSE_ROOT = Path(__file__).resolve().parent

# Source datasets used as inputs by exercises and labs.
DATA_DIR = ITSE_ROOT / "data"

# Output folder for files generated by scripts (reports, exports, temp data).
GENERATED_DIR = ITSE_ROOT / "generated"


def data_file(name: str) -> Path:
    """Return a full path for a file inside `data/`.

    Args:
        name: File name (or relative subpath) under `data/`.

    Returns:
        A `Path` object pointing to `labs/ITSE-1003/data/<name>`.
    """
    return DATA_DIR / name
